# Application names (regex) -------------------------------------------------------------
WORK_APPS: 
- 'terminal\.exe'
- 'code\.exe'
- 'notion\.exe'
- 'windowsterminal\.exe'
- 'githubdesktop\.exe'
- 'notepad\.exe'
- 'photo\.exe'
PERSONAL_APPS: 
- 'signal\.exe'
- 'discord\.exe'
- 'steam\.exe'
- 'mpc-hc64\.exe'
- 'firefox\.exe'
- 'sandrock\.exe'
- 'digikam\.exe'
- 'cheatengine'

# Domain names (regex) ------------------------------------------------------------------
WORK_DOMAINS:
- 'localhost:\d+'
- 'openai'
- 'dash-bootstrap-components'
- 'file:\/\/'
- 'stackoverflow'
- 'edx\.org'
- 'coursera\.org'
- 'desmos\.com'
- 'support\.google'
- 'github'
- 'pytest\.org'
- 'visualstudio\.com'
- '.*\.pycqa\.org'
- 'regex'
- 'plotly'
- 'pandas\.pydata'
- 'w3schools'
- 'python\.'
- 'sql'
- 'geeksforgeeks'
- 'gitguardian'
- 'ubuntu'
- 'learn'
- 'microsoft'
- 'python'
- 'docs'
- 'dash-'
- 'flaticon'
- 'pypi\.org'
- 'mixkit'
- 'wiki'
PERSONAL_DOMAINS:
- 'youtube'
- 'mercadolivre'
- 'hbomax'
- 'tv\.apple'

# Window title keywords (regex) ---------------------------------------------------------
WORK_KEYWORDS:
- 'pandas'
- 'dash'
- 'datascience'
- 'dash-bootstrap'
- 'python'
- 'algorithm'
- 'katex'
- '\.pdf'
- 'code'
- 'debug'
PERSONAL_KEYWORDS:
- 'episode'
- 'whatsapp'
- 'photos'
