HIDDEN_APPS:
  - firefox\.exe
  - explorer\.exe
  - photos\.uwp
FULLSCREEN_APPS:
  - sandrock\.exe
  - mpc-hc64\.exe
WORK_APPS:
  - BREAK\ TIME
  - terminal\.exe
  - code\.exe
  - windowsterminal\.exe
  - githubdesktop\.exe
  - calculator\.uwp
  - camera\.uwp
  - taskmgr\.exe
PERSONAL_APPS:
  - signal\.exe
  - discord\.exe
  - steam.+\.exe
  - firefox\.exe
  - photos\.uwp
  - minecraft\.exe
WORK_DOMAINS:
  - localhost:\d+
  - mail\.google
  - w3resource
  - mathway\.com
  - linkedin\.com
  - vscode\.dev
  - drive\.google
  - file:\/\/
  - stackoverflow
  - edx\.org
  - coursera\.org
  - desmos\.com
  - github
  - codepen\.io
  - mega\.nz
  - pytest\.org
  - pandas\.pydata
  - pypi\.org
  - calendar\.google\.com
  - chrome.*\:\/\/
PERSONAL_DOMAINS:
  - youtube
  - steamcommunity\.com
  - instagram\.com
  - tv\.apple
WORK_KEYWORDS:
  - pandas
  - dash
  - datascience
  - dash-bootstrap
  - python
  - algorithm
  - katex
  - \.pdf
  - code
  - debug
PERSONAL_KEYWORDS:
  - episode
  - playthrough
...
