HIDDEN_APPS:
  - firefox\.exe
  - mpc-hc64\.exe
  - explorer\.exe
FULLSCREEN_APPS:
  - sandrock\.exe
  - mpc-hc64\.exe
WORK_APPS:
  - terminal\.exe
  - code\.exe
  - notion\.exe
  - windowsterminal\.exe
  - githubdesktop\.exe
  - notepad\.exe
  - photo\.exe
  - seccenter\.exe
PERSONAL_APPS:
  - signal\.exe
  - discord\.exe
  - steam.+\.exe
  - mpc-hc64\.exe
  - firefox\.exe
  - sandrock\.exe
  - digikam\.exe
  - cheatengine
WORK_DOMAINS:
  - localhost:\d+
  - \d+\.\d+\.\d+\.\d+
  - openai
  - dash-bootstrap-components
  - file:\/\/
  - stackoverflow
  - huggingface\.co
  - edx\.org
  - coursera\.org
  - desmos\.com
  - support\.google
  - github
  - pytest\.org
  - visualstudio\.com
  - .*\.pycqa\.org
  - regex
  - plotly
  - pandas\.pydata
  - w3schools
  - python\.
  - sql
  - geeksforgeeks
  - gitguardian
  - ubuntu
  - learn
  - microsoft
  - python
  - docs
  - dash-
  - flaticon
  - pypi\.org
  - mixkit
  - wiki
  - physic
  - translate
  - bitdefender
  - khanacademy
  - programiz
PERSONAL_DOMAINS:
  - youtube
  - reddit
  - mercadolivre
  - hbomax
  - tv\.apple
WORK_KEYWORDS:
  - pandas
  - dash
  - datascience
  - dash-bootstrap
  - python
  - algorithm
  - katex
  - \.pdf
  - code
  - debug
PERSONAL_KEYWORDS:
  - episode
  - whatsapp
  - photos
...
