# Goal variables ----------------------------------------------------------------------------------
WORK_DAILY_GOAL: 3                  # Work goal for heatmaps
SMALL_WORK_DAILY_GOAL: 0.5          # Work goal for consistency sake
PERSONAL_DAILY_GOAL: 3              # Personal activity threshold for heatmaps
WORK_TO_PERSONAL_MULTIPLIER: 2      # PERSONAL_DAILY_GOAL override for work done times this,
                                    # bigger value is used, set to 0 to ignore
BRONZE_STREAK_VALUE: 10             # Percentage of goal streak to display bronze crown
SILVER_STREAK_VALUE: 28             # Percentage of goal streak to display silver crown
RED_STREAK_VALUE: 42                # Percentage of goal streak to display red crown
GOLD_STREAK_VALUE: 70               # Percentage of goal streak to display gold crown
ENCHANTED_GOLD_STREAK_VALUE: 85     # Percentage of goal streak to display enchanted gold crown

# Time variables ----------------------------------------------------------------------------------
IDLE_TIME: 120                     # Time without interaction before considered idle
IDLE_CHECK_INTERVAL: 5             # Time between checking for idle
ACTIVITY_CHECK_INTERVAL: 1         # Time between checking for interaction
PARTIAL_CATEGORIES_INTERVAL: 15   # Time between updating total and categories database
MINIMUM_ACTIVITY_TIME: 30          # Minimum time for activity to show in cards
UNRESPONSIVE_THRESHOLD: 10         # Minimum time without backend update before server restart
RETRY_ATTEMPS: 5                   # Retry attempts for various IO operations
GMT_OFFSET: -3                     # Your localtime GMT offset
ADVISOR_CHECK_INTERVAL: 30         # Time between study advisor checks
BACKUP_INTERVAL: 15                # Time between backups of main activity database (in minutes)
NUMBER_OF_BACKUPS: 20              # How many backups you wish to have

# Sizes -------------------------------------------------------------------------------------------
CATEGORY_HEIGHT: 250             # Size of categories graph
CATEGORY_FONT_SIZE: 18           # Font size of hour text
DIVISION_PADDING: 10             # Space between sections
SIDE_PADDING: 20                 # Space between sections and the side of the page
TROUBLESHOOTING_HEIGHT: 900      # Size of troubleshooting page's graph
CARD_PADDING: 6                  # Padding around the elements of a card
CATEGORY_CARD_MARGIN: 6          # Margin between category cards
CATEGORY_COLUMN_SPACE: 2        # Space between the category card columns
GOALS_HEATMAP_HEIGHT: 150        # Height of the heatmap graphs
GOALS_HEATMAP_GAP: 3             # Gap between the squares of the heatmap graph
GOALS_HEATMAP_DIVISION: 35       # Space between heatmap graphs

# Colors ------------------------------------------------------------------------------------------
BACKGROUND: "rgb(30, 30, 30)"                          # Background color of the entire website
TEXT_COLOR: "rgb(255, 255, 255)"                       # Text color for all website text
CARD_COLOR: "rgb(43, 43, 43)"                          # Background color of activity cards
CARD_OUTLINE_COLOR: "rgb(39, 70, 83)"                  # Color for the outline of the cards
CATEGORY_CARD_PERCENTAGE_COLOR: "rgb(168, 212, 255)"   # Text color for activity time's part total
NEUTRAL_COLOR: "rgb(255, 204, 204)"                    # Categories graph neutral color
PERSONAL_COLOR: "rgb(170, 0, 255)"                     # Categories graph personal color
WORK_COLOR: "rgb(170, 191, 238)"                       # Categories graph work
HEATMAP_BASE_COLOR: "rgb(36, 41, 40)"                  # Color indicating a base value
HEATMAP_GOOD_COLOR: "rgb(22, 105, 52)"                 # Color indicating a good value
HEATMAP_OKAY_COLOR: "rgb(110, 110, 0)"                 # Color indicating an okay value
HEATMAP_BAD_COLOR: "rgb(115,23,54)"                  # Color indicating a bad value

...
