# Time variables ----------------------------------------------------------------------------------
IDLE_TIME: 240                   # Time without interaction before considered idle
IDLE_CHECK_INTERVAL: 5           # Time between checking for idle
ACTIVITY_CHECK_INTERVAL: 1       # Time between checking for interaction
MINIMUM_ACTIVITY_TIME: 60        # Minimum time for activity to show in cards
UNRESPONSIVE_THRESHOLD: 5        # Minimum time without backend update before server restart
RETRY_ATTEMPS: 5                 # Retry attempts for various IO operations

# Sizes -------------------------------------------------------------------------------------------
CATEGORY_HEIGHT: 300             # Size of categories graph
CATEGORY_FONT_SIZE: 18           # Font size of hour text
DIVISION_PADDING: 10             # Space between sections
SIDE_PADDING: 20                 # Space between sections and the side of the page
TROUBLESHOOTING_HEIGHT: 900      # Size of troubleshooting page's graph
CARD_PADDING: 3                  # Padding around the elements of a card
CATEGORY_CARD_MARGIN: 6          # Margin between category cards
CATEGORY_COLUMN_SPACE: 15        # Space between the category card columns

# Colors ------------------------------------------------------------------------------------------
BACKGROUND: "rgb(30, 30, 30)"                           # Background color of the entire website
TEXT_COLOR: "rgb(255, 255, 255)"                        # Text color for all website text
CARD_COLOR: "rgb(43, 43, 43)"                           # Background color of activity cards
CARD_OUTLINE_COLOR: "rgb(80, 80, 80)"          # Color for the outline of the cards
CATEGORY_CARD_PERCENTAGE_COLOR: "rgb(168, 212, 255)"    # Text color for activity time's part total
NEUTRAL_COLOR: "rgb(255, 204, 204)"                     # Categories graph neutral color
PERSONAL_COLOR: "rgb(170, 0, 255)"                      # Categories graph personal color
WORK_COLOR: "rgb(170, 170, 255)"                        # Categories graph work                                                                      

# Path for files ----------------------------------------------------------------------------------
URLS_PATH: "C:/Users/pedro/Downloads/EXTENSION/"        # Where the extension downloads the files
...
